#!/bin/bash
function suubnets {
	echo "*********************************************"
	echo "**Getting SUBNETS Info VPC $VPC in region $REGION**"
	echo "*********************************************"
	aws ec2 describe-subnets --filters "Name=vpcid,values=$VPC" --region $REGION | jq ".Subnets[].SubnetId" | tr -d '"'
	echo "------------------------------------------"
}

function sg {
	echo "******************************************************"
	echo "**Getting security group info VPC $VPC in region $REGION**"
	echo "***********************************************************"
	aws ec2 describe-security-groups --filters "Name=vpc-id,value=$VPC" --region $REGION | jq ".SecurityGroups[].GroupName" | tr -d '"'
	echo "--------------------------------------------------------"

}

vpcs() {
	for REGION in $@; do
		echo "Getting VPC List FOR Regions $REGION..."
		vpcs=$(aws ec2describe-vpcs --region "${REGION}" | jq ".Vpcs[].VpcId" | tr -d '"')
		echo $vpcs
		echo "---------------------------------------------------------------------"
		for VPC in $vpcs; do
			subnets $VPC
		done
		for VPC in $vpcs; do
			sg $VPC
		done
	done

}

vpcs "us-east-2 us-west-2 ap-south-1 eu-west-2"


